[versions]
reflections-version = "0.9.12"
junit-version = "5.7.1"
assertj-version = "3.19.0"

[libraries]
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections-version" }
junit-jupier-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-version" }
junit-jupier-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-version" }
junit-jupier-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-version" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-version" }

[bundles]
junit = ["junit-jupier-api", "junit-jupier-params"]
junitRuntime = ["junit-jupier-engine"]
